name: NPM

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

  push:
    branches:
      - main
      - next
      - dev

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      # Publish @seyuna/ui to npm with branch name as tag
      - name: Publish @seyuna/ui
        run: |
          deno run -A build_npm.ts
          cd npm
          echo "Publishing @seyuna/ui..."

          if [ -f "package.json" ]; then
            NAME=$(node -p "require('./package.json').name")
            VERSION=$(node -p "require('./package.json').version")
            BRANCH_NAME=${GITHUB_REF_NAME}

            if npm show "$NAME@$VERSION" &>/dev/null; then
              echo "Version $VERSION of $NAME already exists, skipping..."
            else
              npm ci
              
              if [ "$BRANCH_NAME" == "main" ]; then
                echo "Publishing with tag: latest"
                npm publish --provenance --access public --tag latest
              else
                echo "Publishing with tag: $BRANCH_NAME"
                npm publish --provenance --access public --tag "$BRANCH_NAME"
              fi
            fi
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
